# Generated by Django 4.0.4 on 2023-06-15 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_bodega'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
    ]
