# Generated by Django 4.0.4 on 2023-06-25 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producto', '0004_alter_producto_oferta_delete_oferta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id_boleta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateField(auto_now_add=True)),
                ('fecha_entrega', models.DateField(blank=True, default='', null=True)),
                ('monto_total', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('Entregado', 'Entregado'), ('Despachado', 'Despachado'), ('Vendido', 'Vendido'), ('Preparacion', 'Preparacion')], max_length=40)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
